version: '3.4'

services:
  mapgenerator.webapp:
    image: ${DOCKER_REGISTRY-}map-generator
    environment:
      - APPDATA=${APPDATA:-~/.mapgenerator}
    build:
      context: .
      dockerfile: src/MapGenerator.WebApp/Dockerfile
