version: '3.4'

services:
  mapgenerator.webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "80:5000"
    volumes:
      - ${APPDATA:-~/.mapgenerator}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA:-~/.mapgenerator}/ASP.NET/Https:/root/.aspnet/https:ro